"""Parity check: SSE event-name constants must stay in sync with the JS constants file.

Extracted from megalodon_ui/schemas.py (deleted in P3.1) where it lived as an
import-time assert.  A real pytest test is preferable because failures surface
with a descriptive message and the file is included in CI rather than silently
skipped on import.

The canonical list of SSE event names is ``megalodon_ui.constants.SSE_EVENT_TYPES``.
The JS-codegen source is ``ui/static/js/constants.js`` (regenerated by
``scripts/gen_js_constants.py``).  We verify both sides here.
"""

from __future__ import annotations

import re
from pathlib import Path

from megalodon_ui.constants import (
    SSE_EVENT_TYPES,
    SSE_CLAIM_CREATE,
    SSE_CLAIM_DONE,
    SSE_FINDING_NEW,
    SSE_HEARTBEAT,
    SSE_HISTORY_APPEND,
    SSE_LAGGING,
    SSE_MISSION_STATUS,
    SSE_PHASE_FLIP,
    SSE_SIGNAL_NEW,
    SSE_STATUS_CHANGE,
    SSE_SYNC,
    SSE_TASK_CHANGE,
)

# The exhaustive set of names that the application supports.
_EXPECTED_NAMES: frozenset[str] = frozenset(
    [
        "status-change",
        "task-change",
        "phase-flip",
        "finding-new",
        "history-append",
        "claim-create",
        "claim-done",
        "signal-new",
        "lagging",
        "heartbeat",
        "mission-status",
        "sync",
    ]
)


def test_sse_event_types_matches_expected_literal_set() -> None:
    """constants.SSE_EVENT_TYPES must contain exactly the expected event names.

    This guards against accidental additions or removals from the canonical tuple
    without updating the expected set above (and therefore without updating the
    JS counterpart and any consumers).
    """
    canonical = frozenset(SSE_EVENT_TYPES)
    missing = _EXPECTED_NAMES - canonical
    extra = canonical - _EXPECTED_NAMES
    assert not missing and not extra, (
        f"SSE_EVENT_TYPES parity failure — "
        f"missing from constants: {missing!r}  "
        f"extra in constants: {extra!r}"
    )


def test_individual_sse_constants_covered_by_event_types_tuple() -> None:
    """Every named SSE_* constant must appear in SSE_EVENT_TYPES.

    Prevents a new SSE_FOO constant being added to constants.py without
    also wiring it into the tuple.
    """
    individual = frozenset(
        [
            SSE_STATUS_CHANGE,
            SSE_TASK_CHANGE,
            SSE_PHASE_FLIP,
            SSE_FINDING_NEW,
            SSE_HISTORY_APPEND,
            SSE_CLAIM_CREATE,
            SSE_CLAIM_DONE,
            SSE_SIGNAL_NEW,
            SSE_LAGGING,
            SSE_HEARTBEAT,
            SSE_MISSION_STATUS,
            SSE_SYNC,
        ]
    )
    canonical = frozenset(SSE_EVENT_TYPES)
    not_in_tuple = individual - canonical
    assert not not_in_tuple, (
        f"SSE constants present as individual names but missing from "
        f"SSE_EVENT_TYPES tuple: {not_in_tuple!r}"
    )


def test_js_constants_file_contains_all_sse_event_types() -> None:
    """ui/static/js/constants.js must export every name in SSE_EVENT_TYPES.

    Catches the case where gen_js_constants.py was not re-run after editing
    megalodon_ui/constants.py.
    """
    js_path = Path(__file__).parents[2] / "ui" / "static" / "js" / "constants.js"
    if not js_path.exists():
        import pytest

        pytest.skip("ui/static/js/constants.js not present — skipping JS parity check")

    js_text = js_path.read_text()
    missing_in_js: list[str] = []
    for name in SSE_EVENT_TYPES:
        # Match the string value anywhere in the JS file (quoted).
        if not re.search(re.escape(f'"{name}"'), js_text):
            missing_in_js.append(name)

    assert not missing_in_js, (
        f"SSE event names present in SSE_EVENT_TYPES but missing from "
        f"ui/static/js/constants.js: {missing_in_js!r}. "
        f"Re-run `python3 scripts/gen_js_constants.py` to regenerate."
    )
