"""V9 M4 — codegen for ui/static/js/constants.js from megalodon_ui/constants.py."""
from __future__ import annotations

import importlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
JS_OUTPUT_PATH = REPO_ROOT / "ui" / "static" / "js" / "constants.js"

BANNER = (
    "// AUTO-GENERATED by scripts/gen_js_constants.py — DO NOT EDIT.\n"
    "// Source: megalodon_ui/constants.py\n"
    "// Regenerate with: python3 scripts/gen_js_constants.py\n"
    "\n"
)


def _emit_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_emit_value(v) for v in value) + "]"
    raise TypeError(f"Unsupported constant type: {type(value).__name__}")


def generate_js() -> str:
    sys.path.insert(0, str(REPO_ROOT))
    mod = importlib.import_module("megalodon_ui.constants")
    lines = [BANNER]
    for name in sorted(dir(mod)):
        if name.startswith("_") or not name.isupper():
            continue
        if name in ("TYPE_CHECKING",):  # imported names to skip
            continue
        value = getattr(mod, name)
        if callable(value) or isinstance(value, type):
            continue
        try:
            emitted = _emit_value(value)
        except TypeError as e:
            raise SystemExit(f"gen_js_constants: {name}: {e}")
        lines.append(f"export const {name} = {emitted};\n")
    return "".join(lines)


def main(argv: list[str]) -> int:
    check_mode = "--check" in argv
    generated = generate_js()
    if check_mode:
        existing = JS_OUTPUT_PATH.read_text(encoding="utf-8") if JS_OUTPUT_PATH.exists() else ""
        if existing != generated:
            print("constants.js OUT OF SYNC with constants.py", file=sys.stderr)
            print("Run: python3 scripts/gen_js_constants.py", file=sys.stderr)
            return 1
        return 0
    JS_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    JS_OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"Wrote {JS_OUTPUT_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
